### ISSUE TITLE
Choose a Development Model

### ISSUE THREAD

**Issue by gliperi** [gliperi/godrive-albania#2]
Deadline: 05/04/2023 23:59
Each group should choose a development model for the application.
Write the appropriate documentation noting the chosen development model alongside the reasoning behind it.

**Comment by kluka10** [comment]
Plan Driven Model – Waterfall Model

GoDrive Albania is a plan-driven software model designed to achieve all the phases required to develop the application. GoDrive Albania is a generic product, based even in the market absences that generate user issues as user requirements which are later translated into important part of the software structure. 

Documentation of each phase of developing the model is a key factor in work organization and its veracity. Using this model will help us to be careful in the designing and its requirements because if there is something to change during the time evolution, step by step processing will lead in better coordination and work division. 

Phase 1 - Requirements Definition
Phase 2 - System and software design
Phase 3 - Implementation and unit testing
Phase 4 - Integration and system testing
Phase 5 - Operation and maintenance
